version: '2'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 45.32.176.202:80:80
      - 45.32.176.202:443:443
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/ssl:/etc/nginx/ssl:ro
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./var/www/letsencrypt:/var/www/letsencrypt
